application: mathblogging
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /content/(.*)
  static_files: content/\1
  upload: content/(.*)
- url: /
  static_files: content/start.html
  upload: content/start.html
- url: .*
  script: main.py
